return {
	Impossible = {
		Title = "Impossible",
		Rating = 999,

		FancyFont = false,
		Color = Color3.fromRGB(255, 255, 255),
		GlobalAnnouncement = false,
	},

	Easy = {
		Title = "Easy",
		Rating = 1,

		FancyFont = false,
		Color = Color3.fromRGB(119, 243, 71),
		GlobalAnnouncement = false,
	},
	Medium = {
		Title = "Medium",
		Rating = 2,

		FancyFont = false,
		Color = Color3.fromRGB(255, 255, 0),
		GlobalAnnouncement = false,
	},
	Hard = {
		Title = "Hard",
		Rating = 3,

		FancyFont = false,
		Color = Color3.fromRGB(255, 124, 0),
		GlobalAnnouncement = false,
	},
	Difficult = {
		Title = "Difficult",
		Rating = 4,

		FancyFont = false,
		Color = Color3.fromRGB(255, 0, 0),
		GlobalAnnouncement = false,
	},
	Challenging = {
		Title = "Challenging",
		Rating = 5,

		FancyFont = false,
		Color = Color3.fromRGB(194, 0, 0),
		GlobalAnnouncement = false,
	},
	Intense = {
		Title = "Easy",
		Rating = 6,

		FancyFont = false,
		Color = Color3.fromRGB(25, 34, 45),
		GlobalAnnouncement = false,
	},
	Remorseless = {
		Title = "Remorseless",
		Rating = 7,

		FancyFont = false,
		Color = Color3.fromRGB(200, 0, 200),
		GlobalAnnouncement = false,
	},
	Insane = {
		Title = "Insane",
		Rating = 8,

		FancyFont = false,
		Color = Color3.fromRGB(255, 0, 0),
		GlobalAnnouncement = true,
	},
	Extreme = {
		Title = "Extreme",
		Rating = 9,

		FancyFont = false,
		Color = Color3.fromRGB(2, 128, 255),
		GlobalAnnouncement = true,
	},
	Terrifying = {
		Title = "Terrifying",
		Rating = 10,

		FancyFont = false,
		Color = Color3.fromRGB(0, 255, 255),
		GlobalAnnouncement = true,
	},
	Catastrophic = {
		Title = "Catastrophic",
		Rating = 11,

		FancyFont = true,
		Color = Color3.fromRGB(255, 255, 255),
		GlobalAnnouncement = true,
	},
	Horrific = {
		Title = "Horrific",
		Rating = 12,

		FancyFont = true,
		Color = Color3.fromRGB(150, 150, 255),
		GlobalAnnouncement = true,
	},
	Unreal = {
		Title = "Unreal",
		Rating = 13,

		FancyFont = true,
		Color = Color3.fromRGB(75, 0, 255),
		GlobalAnnouncement = true,
	},
}
