--[[

fanofpixels' Multi-Tower Kit
Version 4.0
Sourced from GitHub @znotfireman/mtk

-------------------------------------------

All MTK scripts and default UI were created by fanofpixels/Ethan Pixelate.
Example Tower 1 & Example Tower 2 built by fanopfixels/Ethan Pixelate.

-------------------------------------------

Credit goes to the JToH team for scripts taken from the JToH Tower Creation Kit v5.4.
Credit for the noclip tool goes to funwolf7

-------------------------------------------

Manual and type documentation .doc file can be found bundled with this place file, or with Ethan himself, feel free to ask for it!

]]
--
