--[[

This is the new (as of 4/21/2020) music script for Juke's Towers of Hecc, made public for tower creators.
The overall layout of the global background music and the music zones is based directly off of Cindering's BGM, which was the music system previously used by KToH/JToH.

There isn't much to adjust, however there is a setting that you can change ("MusicUseSmoothTransition" on line 10, if enabled then it gives you a smooth music transition)
Music zones can be at any rotation and size, but it doesn't work with any other shape aside from Block.
Put the "Music" folder inside this module into ServerScriptService for best effects, and be sure to enable the Insert script.

Part of the main script that is used to determine whether or not the player is inside a music zone was given to me by funwolf7.

You can use this anywhere, but please credit Jukereise for it.

--]]
